# Generated by Django 3.2.13 on 2022-06-06 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=1)),
                ('directions', models.CharField(blank=True, max_length=255)),
                ('measure_amount', models.IntegerField(default=0)),
                ('measure_type', models.CharField(choices=[('GRAMS', 'Grams'), ('CUPS', 'Cups'), ('OUNCES', 'Ounces'), ('LBS', 'Pounds')], default='CUPS', max_length=255)),
                ('ingredient', models.CharField(default='Ingredient', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('DESSERT', 'Dessert')], default='DESSERT', max_length=255)),
                ('recipe_name', models.CharField(blank=True, max_length=255)),
                ('prep_time', models.IntegerField(default=0)),
                ('cook_time', models.IntegerField(default=0)),
                ('cook_temp', models.IntegerField(default=0)),
                ('yield_name', models.CharField(blank=True, max_length=255)),
                ('yield_quantity', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
