# Generated by Django 3.2.13 on 2022-06-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_delete_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.CharField(default='Ingredient', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='measure_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='measure_type',
            field=models.CharField(choices=[('GRAMS', 'Grams'), ('CUPS', 'Cups'), ('OUNCES', 'Ounces'), ('LBS', 'Pounds')], default='CUPS', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_number',
            field=models.IntegerField(default=1),
        ),
    ]
