# Generated by Django 3.2.13 on 2022-06-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220606_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='phase',
            field=models.CharField(default='DRAFT', max_length=255),
        ),
    ]
